---
- name: Install personal development machine
  hosts: localhost
  tasks:
    - ansible.builtin.import_role:
        name: dotfiles
      tags: dotfiles

    - ansible.builtin.import_role:
        name: system-configs
      tags: system-configs

    # Install all standard packages (pacman, AUR, apt)
    - ansible.builtin.import_role:
        name: packages
      tags: packages

    # Install tools requiring custom installation methods
    - ansible.builtin.import_role:
        name: custom-installs
      tags: custom-installs

    - ansible.builtin.import_role:
        name: opencode
      tags: opencode

    - ansible.builtin.import_role:
        name: fonts
      tags: fonts

    - ansible.builtin.import_role:
        name: x11
      tags: x11

    - ansible.builtin.import_role:
        name: ufw
      tags: ufw
