# Configuration for Alacritty, the GPU enhanced terminal emulator

# General root-level configuration
import = ["~/.config/alacritty/dracula.toml",]
shell = "/usr/bin/zsh"

[window]
padding = { x = 10, y = 10 }

[font]
  # The normal (roman) font face to use.
  # Style can be specified to pick a specific face.
  normal = { family = "MesloLGS Nerd Font", style = "Regular"}

