---
- name: Download i3 keyring
  ansible.builtin.get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb
    dest: /tmp/sur5r-keyring.deb
    checksum: sha256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734

- name: Install keyring
  become: true
  ansible.builtin.apt:
    deb: /tmp/sur5r-keyring.deb

- name: Get Ubuntu codename
  ansible.builtin.shell: grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=
  register: ubuntu_codename
  changed_when: false

- name: Add i3 repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb http://debian.sur5r.net/i3/ {{ ubuntu_codename.stdout }} universe"
    filename: sur5r-i3
    state: present

- name: Install i3 and i3status
  become: true
  ansible.builtin.apt:
    name: 
      - i3
      - i3status
    update_cache: true
