---
- name: Check if WezTerm is installed
  ansible.builtin.shell: command -v wezterm
  register: wezterm_exists
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Install WezTerm
  when: wezterm_exists.rc != 0
  block:
    - name: Create keyrings directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install WezTerm GPG key
      ansible.builtin.get_url:
        url: https://apt.fury.io/wez/gpg.key
        dest: /tmp/wezterm.gpg
        mode: '0644'
      register: gpg_download

    - name: Dearmor GPG key
      become: true
      ansible.builtin.shell: cat /tmp/wezterm.gpg | gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg
      changed_when: gpg_download.changed

    - name: Add WezTerm repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *
        state: present
        filename: wezterm

    - name: Install WezTerm
      become: true
      ansible.builtin.apt:
        name: wezterm
        state: present
        update_cache: true

    - name: Clean up temporary GPG key
      ansible.builtin.file:
        path: /tmp/wezterm.gpg
        state: absent
      when: gpg_download.changed

- name: Set WezTerm as default terminal
  become: true
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/open-wezterm-here
    state: selected
