---
- name: Check NeoVim version
  shell: nvim --version | head -n 1 | cut -d ' ' -f 2
  register: nvim_exists
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Install NeoVim if not installed
  when: nvim_exists is failed or nvim_exists.stdout != neovim_version
  block:
    - name: Install nvim build dependencies in Ubuntu
      become: true
      apt:
        name:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
        state: present

    - name: Clean git repository
      ansible.builtin.command:
        chdir: dependencies/neovim
        cmd: git clean -fdx
      changed_when: false

    - name: Get VIMRUNTIME path
      shell: nvim --headless -c 'echo $VIMRUNTIME' -c quit
      register: nvim_vimruntime
      changed_when: false

    - name: Check if previous build exist
      stat: 
        path: dependencies/neovim/build
      register: nvim_build

    - name: Build nvim release version in Linux
      community.general.make:
        chdir: dependencies/neovim
        params:
          CMAKE_BUILD_TYPE: Release
      register: nvim_build_result
      changed_when: nvim_build_result.changed

    - name: Uninstall previous installation of nvim
      become: true
      ansible.builtin.command:
        chdir: dependencies/neovim
        cmd: cmake --build build/ --target uninstall
      when: nvim_build.stat.exists

    - name: Delete previous installation VIMRUNTIME path
      become: true
      file:
        path: "{{ nvim_vimruntime.stderr }}"
        state: absent
      when: nvim_runtime is defined

    - name: Install nvim release version in Linux
      become: true
      community.general.make:
        chdir: dependencies/neovim
        target: install
      register: nvim_install
      changed_when: nvim_install.changed

    - name: Install dependencies for nvim plugins
      become: true
      ansible.builtin.apt:
        name:
          - imagemagick
          - libmagickwand-dev
          - luarocks
          - python3-venv
        update_cache: yes
        state: present
